#define SPARSE_THRESHOLD 0.5
#define EPSILON 10
#define DELIM ','
#define END_COMMAND '\n'
#define DEC_POINT '.'
#define L_FUNC_PAR '('
#define R_FUNC_PAR ')'
#define L_MAT_PAR '['
#define R_MAT_PAR ']'
#define VAR_IDENTIFIER '$'
#define FILE_IDENTIFIER '@'
#define SET_VAR "="
#define WRITE_TO_FILE "<"
#define WRITE_PRIORITY 0